### PR TITLE
LEAN-2306: AMI-020 - Remove invalid attribute - Implementation

### PR DESCRIPTION
**Pull request by nghazzawi-atypon**

### CODE REVIEW

**Comment by nghazzawi-atypon** [comment]
@asouqi  kindly your advice if other files like "ContributorRolesSelect" should be archived..thanks

**Comment by asouqi** [comment]
> kindly your advice if other files like "ContributorRolesSelect" should be archived..thanks

oh, we should not remove them as we need to show them for the dashboard, in LEAN-2305 it says we need to remove them just for ops app so we need to add props to hide them for ops.

and in the article editor, you could use an [environment variable](https://github.com/Atypon-OpenSource/manuscripts-article-editor/blob/master/src/config.ts#L31) like:
```
author: {
  contributions: boolean
  jointAuthorship: boolean
}
```
then will add new environment variables in both [dashboard](https://github.com/atypon/leanworkflow-dashboard/blob/master/webpack.common.js#L86) and [ops](https://github.com/atypon/leanworkflow-ops/blob/master/webpack.common.js#L86) to control their visibility

**Review by asouqi — CHANGES_REQUESTED** [review]
**before you start working on environment variables**, can you please ask Panos if we need them in the dashboard if not you could proceed with your PR immediately.

**Comment by nghazzawi-atypon** [comment]
> **before you start working on environment variables**, can you please ask Panos if we need them in the dashboard if not you could proceed with your PR immediately.

@asouqi  as per Nick comment on https://jira.atypon.com/browse/LEAN-2306, we need this change on the editor level (both apps)

**Review by asouqi — APPROVED** [review]

**Pull request merged**
